output: docs
clean: true
objc: true
umbrella_header: ./Sources/STV/include/SensibleTableView.h
# framework_root: 
sdk: iphonesimulator
# hide_declarations:
# config:
# build_tool_arguments:
# xcodebuild_arguments:
# sourcekitten_sourcefile:
source_directory: ./Sources/STV/
# exclude:
# include:
# swift_version:
swift_build_tool: spm
author: dgApps
author_url: http://dgapps.ie/
module: STV
module_version: 6.0.0
# title:
copyright: "&copy; Copyright 2010 - 2019 [Sensible Cocoa](http://sensiblecocoa.com/) and &copy; Copyright 2019  [dgApps](http://dgapps.ie/)"
readme: README.md
# documentation: ./*.md
# abstract:
# podspec:
# docset_icon:
# docset_path:
root_url: https://github.com/daveguerin/Documents
dash_url: https://github.com/daveguerin/docsets/STV.xml
github_url: https://github.com/daveguerin/STV/
github_file_prefix: https://github.com/daveguerin/STV/tree/master/Sources/STV/
# disable_search:
skip_undocumented: false
# min_acl:
hide_documentation_coverage: false
# custom_categories:
# head:
theme: apple
# use_safe_filenames:
# undocumented_text:
