output: ../../@Documentation/STVDocumentation/docs
clean: false
objc: true
umbrella_header: ./Sources/STV/include/SensibleTableView.h
sdk: iphonesimulator
source_directory: ./Sources/STV/
swift_build_tool: spm
author: dgApps
author_url: http://dgapps.ie/
module: STV
module_version: 6.0.1(13)
copyright: '&copy; Copyright 2010 - 2019 [Sensible Cocoa](http://sensiblecocoa.com/)
  and &copy; Copyright 2019  [dgApps](http://dgapps.ie/)'
readme: README.md
documentation: ./*.md
root_url: https://daveguerin.github.io/STVDocumentation/
dash_url: https://daveguerin.github.io/STVDocumentation/docsets/STV.xml
github_url: https://github.com/daveguerin/STV/
github_file_prefix: https://github.com/daveguerin/STV/tree/master/Sources/STV/
skip_undocumented: false
hide_documentation_coverage: false
theme: fullwidth
